# Generated by Django 5.1 on 2024-09-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='img_url',
            field=models.URLField(default='https://example.com/default-image.jpg', max_length=1024),
        ),
    ]
