# Generated by Django 5.1 on 2024-09-04 07:18

import django.db.models.deletion
from django.db import migrations, models


def create_categories(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    Category.objects.bulk_create([
        Category(name='VEG'),
        Category(name='NON_VEG'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_remove_foodrecipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
    ]
