# Generated by Django 5.1 on 2024-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_foodrecipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrecipe',
            name='Category',
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='category',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON-VEG', 'Non-Vegetarian')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
